spring:
  profiles:
    active: local
---

jwtSecretKey: ENC(HvtNdNbze/htNthbiN2a7+PIkgtHrxO4m4SjoX9GalZZxU4KPyX+E9CsWmRaGgxJ0GMb+DJOyyylHfViXuwyyKt2jtqO2Ps06ugApWcoeAVH5EGY8eOzBukkDtOLix96Uw0fvAFiS1Dr5i6PR1mpcw==)

storage:
  endpoint: https://kr.object.ncloudstorage.com
  access-key: ENC(jqppedRAMM3B4pjB3h3orheellQWd+taO0sEb3PtWnwdQ2WyHgF97Jtysz1x5Ch2jy96B8+nrtgc1jpfyHTokg==)
  secret-key: ENC(CLWYwkC0aY4d0du0vGuAgznwRiPCspEPqbY2hXFbw49yvQp7RZt0Bn2nEisB2nt+ktFbhgzctxvtrxoIao3Bls98jerRAiMQ6N2PGrHgPT8=)

---

spring:
  config:
    activate:
      on-profile: local

mongo:
  url: mongodb://localhost:27017

---

spring:
  config:
    activate:
      on-profile: real
  data:
    mongodb:
      uri: ENC(3K3HJ3bhtUBOxoYfaL1KrP7AF+8cVjIx+KqwxSadrBBcwoIyrHhr8C2CKLGQlE/fMbgHyyZpUAJL6fQzohCNBjf25S3dzeuBs7StySfC1FtGXAFwByLW5A3mumd2o6Nthu+kq1x0xl2nl/o658K0fViUnQn3zEtJndVtv/gi+b9Bo2bBdgtQlWFZbBMVmYygAFbvb7ud1ksIUigUn6vshlbxLS1YV/+5eub0TTed2ebwD9xpEhPaN8oi8uXdpLtuol6408+qEApAkBPYgQMNug==)
      host: ENC(5djq9uUxXVfOik71Gw9R3DyLn4kOEgBTuIK4G2d3cqM3L5T+bkbpqrI33LaSSDC9DVNWI145sgBUC0TaVOrYfSVuwvftpR7y5TI6c+6W5g3Pf598Z2M4qfHYmsyFhHAUVL9844k3A+eayzEBT5dipJBkSmd1oKv7cIpQ2MDJDbk=)
      port: 17017
      database: awesome
      username: ENC(PGZ7CFAgk4ae3WCHNxbYS/NalfkE1ewCWMFG7mRoZdhA5CfEnCsPM5DtQLNlsBDq)
      password: ENC(0sLb6Dokoxa3EwW8iQlhbSKeDSkckTVTs86eCIM9/9wzKomQ3OVJFs7cwTZB/DXt)
      replica-set-name: rational31001
server:
  port: 8081


mongo:
  url: ENC(3K3HJ3bhtUBOxoYfaL1KrP7AF+8cVjIx+KqwxSadrBBcwoIyrHhr8C2CKLGQlE/fMbgHyyZpUAJL6fQzohCNBjf25S3dzeuBs7StySfC1FtGXAFwByLW5A3mumd2o6Nthu+kq1x0xl2nl/o658K0fViUnQn3zEtJndVtv/gi+b9Bo2bBdgtQlWFZbBMVmYygAFbvb7ud1ksIUigUn6vshlbxLS1YV/+5eub0TTed2ebwD9xpEhPaN8oi8uXdpLtuol6408+qEApAkBPYgQMNug==)

